# Generated by Django 3.0.7 on 2020-09-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_userofapp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userofapp',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
