# Generated by Django 3.0.7 on 2020-09-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='no_guests',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
