# Generated by Django 3.0.7 on 2020-09-12 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20200912_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Luxury', 'Luxury')], max_length=10),
        ),
    ]
